In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [76]:
df = pd.read_csv('C:/Users/admin/Downloads/German_Credit_Card.csv')

In [96]:
df.head(10)

,checkin_acc,duration,credit_history,amount,savings_acc,present_emp_since,inst_rate,personal_status,residing_since,age,inst_plans,num_credits,job,status
0,A11,6,A34,1169,A65,A75,4,A93,4,67,A143,2,A173,0
1,A12,48,A32,5951,A61,A73,2,A92,2,22,A143,1,A173,1
2,A14,12,A34,2096,A61,A74,2,A93,3,49,A143,1,A172,0
3,A11,42,A32,7882,A61,A74,2,A93,4,45,A143,1,A173,0
4,A11,24,A33,4870,A61,A73,3,A93,4,53,A143,2,A173,1
5,A14,36,A32,9055,A65,A73,2,A93,4,35,A143,1,A172,0
6,A14,24,A32,2835,A63,A75,3,A93,4,53,A143,1,A173,0
7,A12,36,A32,6948,A61,A73,2,A93,2,35,A143,1,A174,0
8,A14,12,A32,3059,A64,A74,2,A91,4,61,A143,1,A172,0
9,A12,30,A34,5234,A61,A71,4,A94,2,28,A143,2,A174,1

In [98]:
df.tail(20)

,checkin_acc,duration,credit_history,amount,savings_acc,present_emp_since,inst_rate,personal_status,residing_since,age,inst_plans,num_credits,job,status
980,A12,30,A34,8386,A61,A74,2,A93,2,49,A143,1,A173,1
981,A14,48,A32,4844,A61,A71,3,A93,2,33,A141,1,A174,1
982,A13,21,A32,2923,A62,A73,1,A92,1,28,A141,1,A174,0
983,A11,36,A32,8229,A61,A73,2,A93,2,26,A143,1,A173,1
984,A14,24,A34,2028,A61,A74,2,A93,2,30,A143,2,A172,0
985,A11,15,A34,1433,A61,A73,4,A92,3,25,A143,2,A173,0
986,A13,42,A30,6289,A61,A72,2,A91,1,33,A143,2,A173,0
987,A14,13,A32,1409,A62,A71,2,A92,4,64,A143,1,A173,0
988,A11,24,A32,6579,A61,A71,4,A93,2,29,A143,1,A174,0
989,A12,24,A34,1743,A61,A75,4,A93,2,48,A143,2,A172,0
990,A14,12,A34,3565,A65,A72,2,A93,1,37,A143,2,A172,0
991,A14,15,A31,1569,A62,A75,4,A93,4,34,A141,1,A172,0
992,A11,18,A32,1936,A65,A74,2,A94,4,23,A143,2,A172,0
993,A11,36,A32,3959,A61,A71,4,A93,3,30,A143,1,A174,0
994,A14,12,A32,2390,A65,A75,4,A93,3,50,A143,1,A173,0
995,A14,12,A32,1736,A61,A74,3,A92,4,31,A143,1,A172,0
996,A11,30,A32,3857,A61,A73,4,A91,4,40,A143,1,A174,0
997,A14,12,A32,804,A61,A75,4,A93,4,38,A143,1,A173,0
998,A11,45,A32,1845,A61,A73,4,A93,4,23,A143,1,A173,1
999,A12,45,A34,4576,A62,A71,3,A93,4,27,A143,1,A173,0

In [82]:
df.iloc[0:5,7:15]

  personal_status  residing_since  age inst_plans  num_credits   job  status
0             A93               4   67       A143            2  A173       0
1             A92               2   22       A143            1  A173       1
2             A93               3   49       A143            1  A172       0
3             A93               4   45       A143            1  A173       0
4             A93               4   53       A143            2  A173       1

In [86]:
df['checkin_acc'].unique

<bound method Series.unique of 0      A11
1      A12
2      A14
3      A11
4      A11
      ...
995    A14
996    A11
997    A14
998    A11
999    A12
Name: checkin_acc, Length: 1000, dtype: object>

In [94]:
X_feature = list(df.columns)
X_feature.remove('status')
encoded_df = pd.get_dummies(df[X_feature],drop_first=True)
print(list(encoded_df.columns))

['duration', 'amount', 'inst_rate', 'residing_since', 'age', 'num_credits', 'checkin_acc_A12', 'checkin_acc_A13', 'checkin_acc_A14', 'credit_history_A31', 'credit_history_A32', 'credit_history_A33', 'credit_history_A34', 'savings_acc_A62', 'savings_acc_A63', 'savings_acc_A64', 'savings_acc_A65', 'present_emp_since_A72', 'present_emp_since_A73', 'present_emp_since_A74', 'present_emp_since_A75', 'personal_status_A92', 'personal_status_A93', 'personal_status_A94', 'inst_plans_A142', 'inst_plans_A143', 'job_A172', 'job_A173', 'job_A174']

In [100]:
df.sum()

checkin_acc          A11A12A14A11A11A14A14A12A14A12A12A11A12A11A11A...
duration                                                         20903
credit_history       A34A32A34A32A33A32A32A32A32A34A32A32A32A34A32A...
amount                                                         3271258
savings_acc          A65A61A61A61A61A65A63A61A64A61A61A61A61A61A61A...
present_emp_since    A75A73A74A74A73A73A75A73A74A71A72A72A73A75A73A...
inst_rate                                                         2973
personal_status      A93A92A93A93A93A93A93A93A91A94A92A92A92A93A92A...
residing_since                                                    2845
age                                                              35546
inst_plans           A143A143A143A143A143A143A143A143A143A143A143A1...
num_credits                                                       1407
job                  A173A173A172A173A173A172A173A174A172A174A173A1...
status                                                             300
dtype: object

In [102]:
df.count()

checkin_acc          1000
duration             1000
credit_history       1000
amount               1000
savings_acc          1000
present_emp_since    1000
inst_rate            1000
personal_status      1000
residing_since       1000
age                  1000
inst_plans           1000
num_credits          1000
job                  1000
status               1000
dtype: int64

In [138]:
x = encoded_df
y = df['status']

In [152]:
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
clf = DecisionTreeClassifier(criterion = 'gini',max_depth = 3)
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [146]:
y_pred = clf.predict(X_test)

In [148]:
from  sklearn import metrics
print("Confusion Matrix is\n",metrics.confusion_matrix(y_pred,y_test))
print("Accuracy is", metrics.accuracy_score(y_pred,y_test))
print("AUC Score is ", metrics.roc_auc_score(y_pred,y_test))

Confusion Matrix is
 [[10  3]
 [ 0  7]]
Accuracy is 0.85
AUC Score is  0.8846153846153846